import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
});

function copyStaticFiles() {
	// const filesToCopy = ["manifest.json", "styles.css"];
	const filesToCopy = ["manifest.json"];
	for (const file of filesToCopy) {
		if (existsSync(file)) {
			try {
				copyFileSync(file, `dist/${file}`);
				console.log(`✅ ${file} copied to dist/`);
			} catch (err) {
				console.error(`❌ Failed to copy ${file}:`, err);
			}
		} else {
			console.warn(`⚠️  ${file} not found, skipping.`);
		}
	}
}

if (prod) {
	await context.rebuild();
	copyStaticFiles()
	process.exit(0);
} else {
	await context.watch();
	copyStaticFiles();
}
